baseURL = "https://geometry-of-relativity.net/"
languageCode = "en-us"
title = "Geometry of Relativity"
theme = "learn"
publishDir = "docs"

[params]
showVisitedLinks = true
editURL = "https://github.com/absoludity/geometry-of-relativity/edit/master/content/"
author = "Michael Nelson"
description = "Investigating Special Relativity through geometry using a branch of mathematics called Geometric Algebra"
