baseURL = "https://geometry-of-relativity.net/"
languageCode = "en-us"
title = "Geometry of Relativity"
theme = "learn"
publishDir = "../geometry-of-relativity-output/docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = false
editURL = "https://github.com/absoludity/geometry-of-relativity-source/edit/master/content/"
author = "Michael Nelson"
description = "Investigating Special Relativity through geometry using a branch of mathematics called Geometric Algebra"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/absoludity/geometry-of-relativity-source"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 20
