baseURL = "https://geometry-of-relativity.net/"
languageCode = "en-us"
title = "Geometry of Relativity"
theme = "learn"
publishDir = "docs"

[params]
showVisitedLinks = true
editURL = ""
author = "Michael Nelson"
description = ""
